# EVEN FIBONACCI NUMBERS
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import sys

evenSum = 2
stop = 4000000
a = 1
b = 2
for i in range(0, stop):
    nextNum = a + b
    if nextNum % 2 == 0:
        evenSum = evenSum + nextNum
    a = b
    b = nextNum
print(sum)
